[package]
name = "jupiter-sns-rewards"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[[test]]
name = "jupiter_sns_rewards_integration"
path = "../../tests/pocketic/jupiter_sns_rewards_integration.rs"

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-stable-structures = { workspace = true }
jupiter-ic-clients = { version = "0.1.0", path = "../../crates/ic-clients" }
jupiter-canister-logging = { version = "0.1.0", path = "../../crates/canister-logging" }
serde = { workspace = true }
hex = { workspace = true }

[features]
debug_api = []

[dev-dependencies]
anyhow = { workspace = true }
candid_parser = "0.1.4"
pocket-ic = { workspace = true }
slog = { workspace = true }
tokio = { workspace = true }
icrc-ledger-types = { workspace = true }

[build-dependencies]
jupiter-build-support = { version = "0.1.0", path = "../../crates/build-support" }
